/*
Routing

With the Routing service you can calculate routes from A to B taking into account vehicle-specific restrictions, traffic situations, toll, emissions, drivers' working hours, service times and opening intervals.

API version: 1.39
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the RoadAhead type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RoadAhead{}

// RoadAhead Name and number of the road ahead.
type RoadAhead struct {
	// The name of the road. It does not depend on the selected language, instead it is presented as it can be found on local signs.
	Name *string `json:"name,omitempty"`
	// The number of the road which may consist of several numbers separated by \"/\".
	Number *string `json:"number,omitempty"`
}

// NewRoadAhead instantiates a new RoadAhead object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRoadAhead() *RoadAhead {
	this := RoadAhead{}
	return &this
}

// NewRoadAheadWithDefaults instantiates a new RoadAhead object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRoadAheadWithDefaults() *RoadAhead {
	this := RoadAhead{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *RoadAhead) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoadAhead) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *RoadAhead) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *RoadAhead) SetName(v string) {
	o.Name = &v
}

// GetNumber returns the Number field value if set, zero value otherwise.
func (o *RoadAhead) GetNumber() string {
	if o == nil || IsNil(o.Number) {
		var ret string
		return ret
	}
	return *o.Number
}

// GetNumberOk returns a tuple with the Number field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoadAhead) GetNumberOk() (*string, bool) {
	if o == nil || IsNil(o.Number) {
		return nil, false
	}
	return o.Number, true
}

// HasNumber returns a boolean if a field has been set.
func (o *RoadAhead) HasNumber() bool {
	if o != nil && !IsNil(o.Number) {
		return true
	}

	return false
}

// SetNumber gets a reference to the given string and assigns it to the Number field.
func (o *RoadAhead) SetNumber(v string) {
	o.Number = &v
}

func (o RoadAhead) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RoadAhead) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Number) {
		toSerialize["number"] = o.Number
	}
	return toSerialize, nil
}

type NullableRoadAhead struct {
	value *RoadAhead
	isSet bool
}

func (v NullableRoadAhead) Get() *RoadAhead {
	return v.value
}

func (v *NullableRoadAhead) Set(val *RoadAhead) {
	v.value = val
	v.isSet = true
}

func (v NullableRoadAhead) IsSet() bool {
	return v.isSet
}

func (v *NullableRoadAhead) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRoadAhead(val *RoadAhead) *NullableRoadAhead {
	return &NullableRoadAhead{value: val, isSet: true}
}

func (v NullableRoadAhead) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRoadAhead) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


