/*
Routing

With the Routing service you can calculate routes from A to B taking into account vehicle-specific restrictions, traffic situations, toll, emissions, drivers' working hours, service times and opening intervals.

API version: 1.39
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CombinedTransportEvent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CombinedTransportEvent{}

// CombinedTransportEvent Issued when a combined transport is entered or exited. Requires _COMBINED_TRANSPORT_EVENTS_ to be requested.
type CombinedTransportEvent struct {
	// The name of the combined transport.
	Name string `json:"name"`
	Type CombinedTransportType `json:"type"`
	AccessType AccessType `json:"accessType"`
	// For **accessType** _ENTER_ this index points to the corresponding event with **accessType** _EXIT_ and vice-versa. Not present otherwise.
	RelatedEventIndex *int32 `json:"relatedEventIndex,omitempty"`
}

type _CombinedTransportEvent CombinedTransportEvent

// NewCombinedTransportEvent instantiates a new CombinedTransportEvent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCombinedTransportEvent(name string, type_ CombinedTransportType, accessType AccessType) *CombinedTransportEvent {
	this := CombinedTransportEvent{}
	this.Name = name
	this.Type = type_
	this.AccessType = accessType
	return &this
}

// NewCombinedTransportEventWithDefaults instantiates a new CombinedTransportEvent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCombinedTransportEventWithDefaults() *CombinedTransportEvent {
	this := CombinedTransportEvent{}
	return &this
}

// GetName returns the Name field value
func (o *CombinedTransportEvent) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CombinedTransportEvent) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CombinedTransportEvent) SetName(v string) {
	o.Name = v
}

// GetType returns the Type field value
func (o *CombinedTransportEvent) GetType() CombinedTransportType {
	if o == nil {
		var ret CombinedTransportType
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *CombinedTransportEvent) GetTypeOk() (*CombinedTransportType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *CombinedTransportEvent) SetType(v CombinedTransportType) {
	o.Type = v
}

// GetAccessType returns the AccessType field value
func (o *CombinedTransportEvent) GetAccessType() AccessType {
	if o == nil {
		var ret AccessType
		return ret
	}

	return o.AccessType
}

// GetAccessTypeOk returns a tuple with the AccessType field value
// and a boolean to check if the value has been set.
func (o *CombinedTransportEvent) GetAccessTypeOk() (*AccessType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccessType, true
}

// SetAccessType sets field value
func (o *CombinedTransportEvent) SetAccessType(v AccessType) {
	o.AccessType = v
}

// GetRelatedEventIndex returns the RelatedEventIndex field value if set, zero value otherwise.
func (o *CombinedTransportEvent) GetRelatedEventIndex() int32 {
	if o == nil || IsNil(o.RelatedEventIndex) {
		var ret int32
		return ret
	}
	return *o.RelatedEventIndex
}

// GetRelatedEventIndexOk returns a tuple with the RelatedEventIndex field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CombinedTransportEvent) GetRelatedEventIndexOk() (*int32, bool) {
	if o == nil || IsNil(o.RelatedEventIndex) {
		return nil, false
	}
	return o.RelatedEventIndex, true
}

// HasRelatedEventIndex returns a boolean if a field has been set.
func (o *CombinedTransportEvent) HasRelatedEventIndex() bool {
	if o != nil && !IsNil(o.RelatedEventIndex) {
		return true
	}

	return false
}

// SetRelatedEventIndex gets a reference to the given int32 and assigns it to the RelatedEventIndex field.
func (o *CombinedTransportEvent) SetRelatedEventIndex(v int32) {
	o.RelatedEventIndex = &v
}

func (o CombinedTransportEvent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CombinedTransportEvent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["type"] = o.Type
	toSerialize["accessType"] = o.AccessType
	if !IsNil(o.RelatedEventIndex) {
		toSerialize["relatedEventIndex"] = o.RelatedEventIndex
	}
	return toSerialize, nil
}

func (o *CombinedTransportEvent) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"type",
		"accessType",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCombinedTransportEvent := _CombinedTransportEvent{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCombinedTransportEvent)

	if err != nil {
		return err
	}

	*o = CombinedTransportEvent(varCombinedTransportEvent)

	return err
}

type NullableCombinedTransportEvent struct {
	value *CombinedTransportEvent
	isSet bool
}

func (v NullableCombinedTransportEvent) Get() *CombinedTransportEvent {
	return v.value
}

func (v *NullableCombinedTransportEvent) Set(val *CombinedTransportEvent) {
	v.value = val
	v.isSet = true
}

func (v NullableCombinedTransportEvent) IsSet() bool {
	return v.isSet
}

func (v *NullableCombinedTransportEvent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCombinedTransportEvent(val *CombinedTransportEvent) *NullableCombinedTransportEvent {
	return &NullableCombinedTransportEvent{value: val, isSet: true}
}

func (v NullableCombinedTransportEvent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCombinedTransportEvent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


