/*
Routing

With the Routing service you can calculate routes from A to B taking into account vehicle-specific restrictions, traffic situations, toll, emissions, drivers' working hours, service times and opening intervals.

API version: 1.38
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ElevationReport type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ElevationReport{}

// ElevationReport Provides information on the topography of the route or leg, i.e. the total ascent and descent. Elevation‑based metrics represent approximate values and may differ from real‑world measurements.  For each leg the constraint ascent − descent = net elevation difference (last point minus first point) is maintained. Because of this, the sum of ascent or descent values across all legs may slightly exceed the corresponding route total.
type ElevationReport struct {
	// Total ascent of the route or leg [m], estimated from sampled elevation data along the route.
	Ascent int32 `json:"ascent"`
	// Total descent of the route or leg [m], estimated from sampled elevation data along the route.
	Descent int32 `json:"descent"`
}

type _ElevationReport ElevationReport

// NewElevationReport instantiates a new ElevationReport object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewElevationReport(ascent int32, descent int32) *ElevationReport {
	this := ElevationReport{}
	this.Ascent = ascent
	this.Descent = descent
	return &this
}

// NewElevationReportWithDefaults instantiates a new ElevationReport object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewElevationReportWithDefaults() *ElevationReport {
	this := ElevationReport{}
	return &this
}

// GetAscent returns the Ascent field value
func (o *ElevationReport) GetAscent() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Ascent
}

// GetAscentOk returns a tuple with the Ascent field value
// and a boolean to check if the value has been set.
func (o *ElevationReport) GetAscentOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Ascent, true
}

// SetAscent sets field value
func (o *ElevationReport) SetAscent(v int32) {
	o.Ascent = v
}

// GetDescent returns the Descent field value
func (o *ElevationReport) GetDescent() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Descent
}

// GetDescentOk returns a tuple with the Descent field value
// and a boolean to check if the value has been set.
func (o *ElevationReport) GetDescentOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Descent, true
}

// SetDescent sets field value
func (o *ElevationReport) SetDescent(v int32) {
	o.Descent = v
}

func (o ElevationReport) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ElevationReport) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["ascent"] = o.Ascent
	toSerialize["descent"] = o.Descent
	return toSerialize, nil
}

func (o *ElevationReport) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"ascent",
		"descent",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varElevationReport := _ElevationReport{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varElevationReport)

	if err != nil {
		return err
	}

	*o = ElevationReport(varElevationReport)

	return err
}

type NullableElevationReport struct {
	value *ElevationReport
	isSet bool
}

func (v NullableElevationReport) Get() *ElevationReport {
	return v.value
}

func (v *NullableElevationReport) Set(val *ElevationReport) {
	v.value = val
	v.isSet = true
}

func (v NullableElevationReport) IsSet() bool {
	return v.isSet
}

func (v *NullableElevationReport) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableElevationReport(val *ElevationReport) *NullableElevationReport {
	return &NullableElevationReport{value: val, isSet: true}
}

func (v NullableElevationReport) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableElevationReport) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


