/*
Routing

With the Routing service you can calculate routes from A to B taking into account vehicle-specific restrictions, traffic situations, toll, emissions, drivers' working hours, service times and opening intervals.

API version: 1.39
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the WorkLogbook type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WorkLogbook{}

// WorkLogbook Defines the accumulated driving, working and travel times since the last break or daily rest. For details see this [concept](./concepts/drivers-working-hours).
type WorkLogbook struct {
	// The last time the driver worked formatted according to [RFC 3339](https://tools.ietf.org/html/rfc3339).    The date must not be before 1970-01-01T00:00:00+00:00 nor after 2037-12-31T23:59:59+00:00.  The date must provide an offset to UTC.   See [here](./concepts/date-and-time) for more information on the relevance of date and time.
	LastTimeTheDriverWorked time.Time `json:"lastTimeTheDriverWorked"`
	// Accumulated driving time since end of last break [s], this includes all time behind the wheel.   Values higher than the maximum driving time between breaks of the **workingHoursPreset** are capped and effectively equal to the value given by the preset. 
	AccumulatedDrivingTimeSinceLastBreak *int32 `json:"accumulatedDrivingTimeSinceLastBreak,omitempty"`
	// Accumulated working time since end of last break [s], this includes driving time, service time at depot and customers, and idle time if lower than working time threshold.     Values higher than the maximum working time between breaks of the **workingHoursPreset** are capped and effectively equal to the value given by the preset. May not be smaller than **accumulatedDrivingTimeSinceLastBreak** if the value is specified. If no other value is specified, the default value is 0. 
	AccumulatedWorkingTimeSinceLastBreak *int32 `json:"accumulatedWorkingTimeSinceLastBreak,omitempty"`
	// Accumulated driving time since end of last daily rest [s], this includes all time behind the wheel.   Values higher than the maximum driving time between daily rests of the **workingHoursPreset** are capped and effectively equal to the value given by preset. May not be smaller than **accumulatedDrivingTimeSinceLastBreak** if the value is specified. If no other value is specified, the default value is 0. 
	AccumulatedDrivingTimeSinceLastDailyRest *int32 `json:"accumulatedDrivingTimeSinceLastDailyRest,omitempty"`
	// Accumulated travel time since end of last daily rest [s], this includes all time since the last daily rest.   Values higher than maximum travel time between daily rests of the **workingHoursPreset** are capped and effectively equal to the value given by the preset. May not be smaller than **accumulatedWorkingTimeSinceLastBreak** or **accumulatedDrivingTimeSinceLastDailyRest** if the values are specified. If no other value is specified, the default value is 0. 
	AccumulatedTravelTimeSinceLastDailyRest *int32 `json:"accumulatedTravelTimeSinceLastDailyRest,omitempty"`
}

type _WorkLogbook WorkLogbook

// NewWorkLogbook instantiates a new WorkLogbook object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWorkLogbook(lastTimeTheDriverWorked time.Time) *WorkLogbook {
	this := WorkLogbook{}
	this.LastTimeTheDriverWorked = lastTimeTheDriverWorked
	var accumulatedDrivingTimeSinceLastBreak int32 = 0
	this.AccumulatedDrivingTimeSinceLastBreak = &accumulatedDrivingTimeSinceLastBreak
	return &this
}

// NewWorkLogbookWithDefaults instantiates a new WorkLogbook object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWorkLogbookWithDefaults() *WorkLogbook {
	this := WorkLogbook{}
	var accumulatedDrivingTimeSinceLastBreak int32 = 0
	this.AccumulatedDrivingTimeSinceLastBreak = &accumulatedDrivingTimeSinceLastBreak
	return &this
}

// GetLastTimeTheDriverWorked returns the LastTimeTheDriverWorked field value
func (o *WorkLogbook) GetLastTimeTheDriverWorked() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.LastTimeTheDriverWorked
}

// GetLastTimeTheDriverWorkedOk returns a tuple with the LastTimeTheDriverWorked field value
// and a boolean to check if the value has been set.
func (o *WorkLogbook) GetLastTimeTheDriverWorkedOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LastTimeTheDriverWorked, true
}

// SetLastTimeTheDriverWorked sets field value
func (o *WorkLogbook) SetLastTimeTheDriverWorked(v time.Time) {
	o.LastTimeTheDriverWorked = v
}

// GetAccumulatedDrivingTimeSinceLastBreak returns the AccumulatedDrivingTimeSinceLastBreak field value if set, zero value otherwise.
func (o *WorkLogbook) GetAccumulatedDrivingTimeSinceLastBreak() int32 {
	if o == nil || IsNil(o.AccumulatedDrivingTimeSinceLastBreak) {
		var ret int32
		return ret
	}
	return *o.AccumulatedDrivingTimeSinceLastBreak
}

// GetAccumulatedDrivingTimeSinceLastBreakOk returns a tuple with the AccumulatedDrivingTimeSinceLastBreak field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkLogbook) GetAccumulatedDrivingTimeSinceLastBreakOk() (*int32, bool) {
	if o == nil || IsNil(o.AccumulatedDrivingTimeSinceLastBreak) {
		return nil, false
	}
	return o.AccumulatedDrivingTimeSinceLastBreak, true
}

// HasAccumulatedDrivingTimeSinceLastBreak returns a boolean if a field has been set.
func (o *WorkLogbook) HasAccumulatedDrivingTimeSinceLastBreak() bool {
	if o != nil && !IsNil(o.AccumulatedDrivingTimeSinceLastBreak) {
		return true
	}

	return false
}

// SetAccumulatedDrivingTimeSinceLastBreak gets a reference to the given int32 and assigns it to the AccumulatedDrivingTimeSinceLastBreak field.
func (o *WorkLogbook) SetAccumulatedDrivingTimeSinceLastBreak(v int32) {
	o.AccumulatedDrivingTimeSinceLastBreak = &v
}

// GetAccumulatedWorkingTimeSinceLastBreak returns the AccumulatedWorkingTimeSinceLastBreak field value if set, zero value otherwise.
func (o *WorkLogbook) GetAccumulatedWorkingTimeSinceLastBreak() int32 {
	if o == nil || IsNil(o.AccumulatedWorkingTimeSinceLastBreak) {
		var ret int32
		return ret
	}
	return *o.AccumulatedWorkingTimeSinceLastBreak
}

// GetAccumulatedWorkingTimeSinceLastBreakOk returns a tuple with the AccumulatedWorkingTimeSinceLastBreak field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkLogbook) GetAccumulatedWorkingTimeSinceLastBreakOk() (*int32, bool) {
	if o == nil || IsNil(o.AccumulatedWorkingTimeSinceLastBreak) {
		return nil, false
	}
	return o.AccumulatedWorkingTimeSinceLastBreak, true
}

// HasAccumulatedWorkingTimeSinceLastBreak returns a boolean if a field has been set.
func (o *WorkLogbook) HasAccumulatedWorkingTimeSinceLastBreak() bool {
	if o != nil && !IsNil(o.AccumulatedWorkingTimeSinceLastBreak) {
		return true
	}

	return false
}

// SetAccumulatedWorkingTimeSinceLastBreak gets a reference to the given int32 and assigns it to the AccumulatedWorkingTimeSinceLastBreak field.
func (o *WorkLogbook) SetAccumulatedWorkingTimeSinceLastBreak(v int32) {
	o.AccumulatedWorkingTimeSinceLastBreak = &v
}

// GetAccumulatedDrivingTimeSinceLastDailyRest returns the AccumulatedDrivingTimeSinceLastDailyRest field value if set, zero value otherwise.
func (o *WorkLogbook) GetAccumulatedDrivingTimeSinceLastDailyRest() int32 {
	if o == nil || IsNil(o.AccumulatedDrivingTimeSinceLastDailyRest) {
		var ret int32
		return ret
	}
	return *o.AccumulatedDrivingTimeSinceLastDailyRest
}

// GetAccumulatedDrivingTimeSinceLastDailyRestOk returns a tuple with the AccumulatedDrivingTimeSinceLastDailyRest field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkLogbook) GetAccumulatedDrivingTimeSinceLastDailyRestOk() (*int32, bool) {
	if o == nil || IsNil(o.AccumulatedDrivingTimeSinceLastDailyRest) {
		return nil, false
	}
	return o.AccumulatedDrivingTimeSinceLastDailyRest, true
}

// HasAccumulatedDrivingTimeSinceLastDailyRest returns a boolean if a field has been set.
func (o *WorkLogbook) HasAccumulatedDrivingTimeSinceLastDailyRest() bool {
	if o != nil && !IsNil(o.AccumulatedDrivingTimeSinceLastDailyRest) {
		return true
	}

	return false
}

// SetAccumulatedDrivingTimeSinceLastDailyRest gets a reference to the given int32 and assigns it to the AccumulatedDrivingTimeSinceLastDailyRest field.
func (o *WorkLogbook) SetAccumulatedDrivingTimeSinceLastDailyRest(v int32) {
	o.AccumulatedDrivingTimeSinceLastDailyRest = &v
}

// GetAccumulatedTravelTimeSinceLastDailyRest returns the AccumulatedTravelTimeSinceLastDailyRest field value if set, zero value otherwise.
func (o *WorkLogbook) GetAccumulatedTravelTimeSinceLastDailyRest() int32 {
	if o == nil || IsNil(o.AccumulatedTravelTimeSinceLastDailyRest) {
		var ret int32
		return ret
	}
	return *o.AccumulatedTravelTimeSinceLastDailyRest
}

// GetAccumulatedTravelTimeSinceLastDailyRestOk returns a tuple with the AccumulatedTravelTimeSinceLastDailyRest field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkLogbook) GetAccumulatedTravelTimeSinceLastDailyRestOk() (*int32, bool) {
	if o == nil || IsNil(o.AccumulatedTravelTimeSinceLastDailyRest) {
		return nil, false
	}
	return o.AccumulatedTravelTimeSinceLastDailyRest, true
}

// HasAccumulatedTravelTimeSinceLastDailyRest returns a boolean if a field has been set.
func (o *WorkLogbook) HasAccumulatedTravelTimeSinceLastDailyRest() bool {
	if o != nil && !IsNil(o.AccumulatedTravelTimeSinceLastDailyRest) {
		return true
	}

	return false
}

// SetAccumulatedTravelTimeSinceLastDailyRest gets a reference to the given int32 and assigns it to the AccumulatedTravelTimeSinceLastDailyRest field.
func (o *WorkLogbook) SetAccumulatedTravelTimeSinceLastDailyRest(v int32) {
	o.AccumulatedTravelTimeSinceLastDailyRest = &v
}

func (o WorkLogbook) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WorkLogbook) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["lastTimeTheDriverWorked"] = o.LastTimeTheDriverWorked
	if !IsNil(o.AccumulatedDrivingTimeSinceLastBreak) {
		toSerialize["accumulatedDrivingTimeSinceLastBreak"] = o.AccumulatedDrivingTimeSinceLastBreak
	}
	if !IsNil(o.AccumulatedWorkingTimeSinceLastBreak) {
		toSerialize["accumulatedWorkingTimeSinceLastBreak"] = o.AccumulatedWorkingTimeSinceLastBreak
	}
	if !IsNil(o.AccumulatedDrivingTimeSinceLastDailyRest) {
		toSerialize["accumulatedDrivingTimeSinceLastDailyRest"] = o.AccumulatedDrivingTimeSinceLastDailyRest
	}
	if !IsNil(o.AccumulatedTravelTimeSinceLastDailyRest) {
		toSerialize["accumulatedTravelTimeSinceLastDailyRest"] = o.AccumulatedTravelTimeSinceLastDailyRest
	}
	return toSerialize, nil
}

func (o *WorkLogbook) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"lastTimeTheDriverWorked",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWorkLogbook := _WorkLogbook{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varWorkLogbook)

	if err != nil {
		return err
	}

	*o = WorkLogbook(varWorkLogbook)

	return err
}

type NullableWorkLogbook struct {
	value *WorkLogbook
	isSet bool
}

func (v NullableWorkLogbook) Get() *WorkLogbook {
	return v.value
}

func (v *NullableWorkLogbook) Set(val *WorkLogbook) {
	v.value = val
	v.isSet = true
}

func (v NullableWorkLogbook) IsSet() bool {
	return v.isSet
}

func (v *NullableWorkLogbook) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWorkLogbook(val *WorkLogbook) *NullableWorkLogbook {
	return &NullableWorkLogbook{value: val, isSet: true}
}

func (v NullableWorkLogbook) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWorkLogbook) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


