/*
Routing

With the Routing service you can calculate routes from A to B taking into account vehicle-specific restrictions, traffic situations, toll, emissions, drivers' working hours, service times and opening intervals.

API version: 1.40
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CombinedTransportLocation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CombinedTransportLocation{}

// CombinedTransportLocation Represents the start or destination location of a combined transport, e.g. the port.
type CombinedTransportLocation struct {
	// The latitude value in degrees (WGS84/EPSG:4326) from south to north.
	Latitude float64 `json:"latitude"`
	// The longitude value in degrees (WGS84/EPSG:4326) from west to east.
	Longitude float64 `json:"longitude"`
}

type _CombinedTransportLocation CombinedTransportLocation

// NewCombinedTransportLocation instantiates a new CombinedTransportLocation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCombinedTransportLocation(latitude float64, longitude float64) *CombinedTransportLocation {
	this := CombinedTransportLocation{}
	this.Latitude = latitude
	this.Longitude = longitude
	return &this
}

// NewCombinedTransportLocationWithDefaults instantiates a new CombinedTransportLocation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCombinedTransportLocationWithDefaults() *CombinedTransportLocation {
	this := CombinedTransportLocation{}
	return &this
}

// GetLatitude returns the Latitude field value
func (o *CombinedTransportLocation) GetLatitude() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.Latitude
}

// GetLatitudeOk returns a tuple with the Latitude field value
// and a boolean to check if the value has been set.
func (o *CombinedTransportLocation) GetLatitudeOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Latitude, true
}

// SetLatitude sets field value
func (o *CombinedTransportLocation) SetLatitude(v float64) {
	o.Latitude = v
}

// GetLongitude returns the Longitude field value
func (o *CombinedTransportLocation) GetLongitude() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.Longitude
}

// GetLongitudeOk returns a tuple with the Longitude field value
// and a boolean to check if the value has been set.
func (o *CombinedTransportLocation) GetLongitudeOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Longitude, true
}

// SetLongitude sets field value
func (o *CombinedTransportLocation) SetLongitude(v float64) {
	o.Longitude = v
}

func (o CombinedTransportLocation) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CombinedTransportLocation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["latitude"] = o.Latitude
	toSerialize["longitude"] = o.Longitude
	return toSerialize, nil
}

func (o *CombinedTransportLocation) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"latitude",
		"longitude",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCombinedTransportLocation := _CombinedTransportLocation{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCombinedTransportLocation)

	if err != nil {
		return err
	}

	*o = CombinedTransportLocation(varCombinedTransportLocation)

	return err
}

type NullableCombinedTransportLocation struct {
	value *CombinedTransportLocation
	isSet bool
}

func (v NullableCombinedTransportLocation) Get() *CombinedTransportLocation {
	return v.value
}

func (v *NullableCombinedTransportLocation) Set(val *CombinedTransportLocation) {
	v.value = val
	v.isSet = true
}

func (v NullableCombinedTransportLocation) IsSet() bool {
	return v.isSet
}

func (v *NullableCombinedTransportLocation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCombinedTransportLocation(val *CombinedTransportLocation) *NullableCombinedTransportLocation {
	return &NullableCombinedTransportLocation{value: val, isSet: true}
}

func (v NullableCombinedTransportLocation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCombinedTransportLocation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


